stages:
    - test
    - release

textlint:
    stage: test
    image: node:latest
    script:
        - npm install -g textlint
        - npm install -g textlint-rule-preset-japanese textlint-rule-preset-ja-technical-writing textlint-rule-prh
        - cd work && textlint test.md


docker-push:
    stage: release
    image: docker:latest
    services:
        - docker:dind
    variables:
        REGISTRY_URL: $CI_REGISTRY
        IMAGE_TAG: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/textlint:0.1
        IMAGE_VERSION: "0.1"
    before_script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    script:
        - echo $CI_REGISTRY_IMAGE
        - echo $IMAGE_TAG
        - echo $CI_PROJECT_NAME
        - docker build -f textlint/Dockerfile -t $CI_REGISTRY_IMAGE:$IMAGE_VERSION textlint/
        - docker push $IMAGE_TAG
        