stages:
    - pre-test
    - release
    - test

textlint-test:
    stage: pre-test
    image: node:latest
    script:
        - npm install -g textlint
        - npm install -g textlint-rule-preset-japanese \
            textlint-rule-preset-ja-technical-writing \
            textlint-rule-preset-ja-spacing \
            textlint-rule-preset-ja-engineering-paper \
            textlint-rule-preset-jtf-style \
            textlint-rule-prh \
            textlint-rule-ja-space-between-half-and-full-width \
            textlint-rule-ja-space-around-code \
            textlint-rule-ja-hiragana-fukushi \
            textlint-rule-ja-hiragana-keishikimeishi \
            textlint-rule-ja-hiragana-hojodoushi \
            @textlint-ja/textlint-rule-no-synonyms sudachi-synonyms-dictionary
        - cd test-custom && textlint success.md

docker-push:
    stage: release
    image: docker:latest
    services:
        - docker:dind
    variables:
        REGISTRY_URL: $CI_REGISTRY
        IMAGE_VERSION: "0.1"
        IMAGE_NAME: textlint
        IMAGE_TAG: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$IMAGE_NAME:$IMAGE_VERSION
    before_script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker login -u $CI_REGISTRY_USER -p $CI_BUILD_TOKEN $REGISTRY_URL
    script:
        - echo $CI_REGISTRY_IMAGE
        - echo $IMAGE_TAG
        - echo $CI_PROJECT_NAME
        - docker build -f textlint/Dockerfile -t $IMAGE_TAG textlint/
        - docker push $IMAGE_TAG
        
docker-textlint-test:
    stage: test
    image: registry.gitlab.com/hassiweb-programming/textlint/textlint:0.1
    script:
        - cd test-custom && textlint success.md

